component: scf
name: wsregister
org: test
app: wsApp
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  runtime: Python2.7
  region: ${env:REGION}
  handler: ws_register.main_handler
  timeout: 30
  #environment:
    #variables:
      #apiid: test