component: scf
name: wsunregister
org: test
app: wsApp
stage: dev

inputs:
  name: ${name}-${stage}
  src: ./
  runtime: Python2.7
  region: ${env:REGION}
  handler: ws_unregister.main_handler
  timeout: 30
  environment:
    variables:
      apiid:  api-npmirrs5 #ws 的 api